# Makefile
run-dist:
	./build/install/app/bin/app

lint:
	./gradlew checkstyleMain checkstyleTest

clean:
	./gradlew clean

build:
	./gradlew clean build

install:
	./gradlew clean install

run:
	./gradlew run

test:
	./gradlew test


.PHONY: build
